import type { ColumnType, Generated } from 'kysely'
import type { Scope } from '../shared/scopes.js'

/**
 * The three modes the engine knows. A union rather than `string`, so a branch on the mode can
 * be made exhaustive: spec 3 adding a fourth gets a compile error at every such branch instead
 * of falling through to whatever the last `if` happened to do.
 */
export type ConcurrencyMode = 'exclusive' | 'shared' | 'pool'

export interface TenantsTable {
  id: Generated<string>
  name: string
  is_active: Generated<boolean>
  created_at: Generated<Date>
}

export interface ApiKeysTable {
  id: Generated<string>
  tenant_id: string
  name: string
  /** The lookup handle, stored in the clear. The secret half is never stored at all. */
  key_prefix: string
  key_hash: string
  /** A set, not a rank. Nothing here implies anything else — see `src/shared/scopes.ts`. */
  scopes: Scope[]
  created_at: Generated<Date>
  last_used_at: ColumnType<Date | null, Date | string | null, Date | string | null>
  revoked_at: ColumnType<Date | null, Date | string | null, Date | string | null>
}

export interface ResourcesTable {
  id: Generated<string>
  tenant_id: string
  timezone: string
  is_active: Generated<boolean>
  /** Postgres interval, read and written as an ISO-8601 string (intervalstyle = iso_8601) */
  slot_duration: string
  /** Postgres time, read as 'HH:MM:SS' */
  slot_anchor_time: Generated<string>
  capacity: Generated<number>
  concurrency_mode: ConcurrencyMode
  /**
   * The pool this resource belongs to, or null. A pool is itself a resource with
   * `concurrency_mode = 'pool'`; see spec 3.
   */
  pool_id: ColumnType<string | null, string | null | undefined, string | null>
  created_at: Generated<Date>
  updated_at: ColumnType<Date, Date | undefined, Date>
}

export interface ScheduleTable {
  id: Generated<string>
  tenant_id: string
  resource_id: string
  day_of_week: number
  start_time: string | null
  end_time: string | null
}

export interface ScheduleExceptionsTable {
  id: Generated<string>
  tenant_id: string
  resource_id: string
  /** Postgres date, read as 'YYYY-MM-DD' */
  date: string
  start_time: string | null
  end_time: string | null
}

export type BookingStatus = 'held' | 'confirmed' | 'cancelled' | 'completed' | 'no_show' | 'expired'

export interface BookingsTable {
  id: Generated<string>
  tenant_id: string
  resource_id: string
  /** An absolute instant. `pg` returns timestamptz as a JS Date. */
  start_time: ColumnType<Date, Date | string, Date | string>
  end_time: ColumnType<Date, Date | string, Date | string>
  /** Generated by Postgres: readable, never writable — the types say so. */
  time_range: ColumnType<string, never, never>
  status: BookingStatus
  /**
   * Opaque, never interpreted, and optional: a caller keeping its own guest records does not
   * need the engine to hold one. It is not inert, though — it is one of the three fields that
   * define what an idempotency key stands for, which is why the column survived rather than
   * being dropped.
   */
  customer_id: string | null
  concurrency_mode: ConcurrencyMode
  held_until: ColumnType<Date | null, Date | string | null, Date | string | null>
  idempotency_key: string | null
  created_at: Generated<Date>
  updated_at: ColumnType<Date, Date | undefined, Date>
}

export interface Database {
  tenants: TenantsTable
  api_keys: ApiKeysTable
  resources: ResourcesTable
  schedule: ScheduleTable
  schedule_exceptions: ScheduleExceptionsTable
  bookings: BookingsTable
}
