import type { ColumnType, Generated } from 'kysely'

/**
 * The three modes the engine knows. A union rather than `string`, so a branch on the mode can
 * be made exhaustive: spec 3 adding a fourth gets a compile error at every such branch instead
 * of falling through to whatever the last `if` happened to do.
 */
export type ConcurrencyMode = 'exclusive' | 'shared' | 'pool'

export interface ResourcesTable {
  id: Generated<string>
  timezone: string
  is_active: Generated<boolean>
  /** Postgres interval, read and written as an ISO-8601 string (intervalstyle = iso_8601) */
  slot_duration: string
  /** Postgres time, read as 'HH:MM:SS' */
  slot_anchor_time: Generated<string>
  capacity: Generated<number>
  concurrency_mode: ConcurrencyMode
  created_at: Generated<Date>
  updated_at: ColumnType<Date, Date | undefined, Date>
}

export interface ScheduleTable {
  id: Generated<string>
  resource_id: string
  day_of_week: number
  start_time: string | null
  end_time: string | null
}

export interface ScheduleExceptionsTable {
  id: Generated<string>
  resource_id: string
  /** Postgres date, read as 'YYYY-MM-DD' */
  date: string
  start_time: string | null
  end_time: string | null
}

export type BookingStatus = 'held' | 'confirmed' | 'cancelled' | 'completed' | 'no_show' | 'expired'

export interface BookingsTable {
  id: Generated<string>
  resource_id: string
  /** An absolute instant. `pg` returns timestamptz as a JS Date. */
  start_time: ColumnType<Date, Date | string, Date | string>
  end_time: ColumnType<Date, Date | string, Date | string>
  /** Generated by Postgres: readable, never writable — the types say so. */
  time_range: ColumnType<string, never, never>
  status: BookingStatus
  customer_id: string
  concurrency_mode: ConcurrencyMode
  held_until: ColumnType<Date | null, Date | string | null, Date | string | null>
  idempotency_key: string | null
  created_at: Generated<Date>
  updated_at: ColumnType<Date, Date | undefined, Date>
}

export interface Database {
  resources: ResourcesTable
  schedule: ScheduleTable
  schedule_exceptions: ScheduleExceptionsTable
  bookings: BookingsTable
}
